# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Build settings
remote_theme: cpmpercussion/alembic

# daviddarnes/alembic@main
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji



# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: acma89 # jekyll-seo-tag > Owners twitter username
author: acma89 # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Australasian Computer Music Association # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/acma89
    - https://www.facebook.com/acma89
    - https://www.instagram.com/aus_computer_music
    - https://github.com/australasian-computer-music-association
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Australia/Canberra # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "News from the Australasian Computer Music Association" # The post list page content
    feature_image: /assets/images/acmc2019-concert-e1618799441533.jpg
  conferences:
    output: true
    permalink: /conferences/:path/
  minutes:
    output: true
    permalink: /minutes/:path/

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "assets/images/acmc2019-concert-e1618799441533.jpg" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
  -
    scope:
      path: _conferences
    values:
      layout: page

# 7. Site settings
title: Australasian Computer Music Association
email: info@computermusic.org.au
description: >- # this means to ignore newlines until "baseurl:"
  The Australasian Computer Music Association was founded in 1989. The organisation provides a forum for new compositions, information sharing, and research about music technology and computer music, principally throughout Australia and New Zealand. The Australasian Computer Music Association is a community of composers, performers, teachers and technologists who have an interest in, are making, or supporting music making with computers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://computermusic.org.au" # the base hostname & protocol for your site, e.g. http://example.com
encoding: "UTF-8" # Make sure the encoding is right
lang: en-GB # Set the site language
logo: "/assets/logos/acma-logo-square-black.svg" # Site logo, also used in jekyll-seo-tag
repo: "https://github.com/australasian_computer_music_association/acma-jekyll"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  180: '/assets/logos/logo@180px.png'
  192: '/assets/logos/logo@192px.png'
  512: '/assets/logos/logo@512px.png'

# 9. Site navigation
navigation_header:
- title: About
  url: /about/
- title: News
  url: /news/
- title: Chroma
  url: /chroma/
- title: Conference
  url: /conferences/
- title: Community
  url: /acma-list/
- title: Committee
  url: /committee/
- title: Membership
  url: /membership/
- title: Search
  url: /search/

#navigation_footer:
#- title: Created by David Darnes
#url: https://darn.es

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/acma89
  Facebook: https://www.facebook.com/acma89
  Instagram: https://www.instagram.com/aus_computer_music
  GitHub: https://github.com/australasian_computer_music_association
  link: https://computermusic.org.au
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Source+Serif+Pro:wght@400;700&display=swap
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap


